# Generated by Django 3.2.7 on 2023-03-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Property Built Date'),
        ),
    ]
