# Generated by Django 3.2.7 on 2023-03-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_built_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='built_date',
            field=models.DateField(blank=True, null=True, verbose_name='Property Built Date'),
        ),
    ]
